services:
  kong:
    image: kong:latest
    container_name: shelly-simulator-kong
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
    ports:
      - "8000:8000"  # Proxy port
      - "8001:8001"  # Admin API port
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    restart: on-failure
    networks:
      - shelly-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shelly-simulator-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SERVER_PORT: 8080
      CORS_ALLOWED_ORIGINS: '*'
    expose:
      - "8080"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: on-failure
    networks:
      - shelly-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shelly-simulator-frontend
    environment:
      VITE_API_BASE_URL: /api
      VITE_GRAPHQL_WS_URL: ws://localhost:8000/graphql
    expose:
      - "80"
    restart: on-failure
    networks:
      - shelly-network

networks:
  shelly-network:
    driver: bridge
